config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  resources :categories, except: :show do
    resources :posts do
    end
  end
  resources :comments, only: [:show, :create]

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, as: :comment_goal, dependent: :destroy

  validates :name, format: { with: /\./,
                               message: 'should include "."' }
  validates :name, format: { with: /\A[A-Z][a-z]+\s+[A-Z][a-z]+\.?\z/,
                               message: 'should have 2 capital words at least 2 characters' }
  validates :description, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :comment_goal, polymorphic: true

  validates :author, format: { with: /\./,
                                message: 'should include "."' }
  validates :author, format: { with: /\A[A-Z][a-z]+\s+[A-Z][a-z]+\.?\z/,
                               message: 'should have 2 capital words at least 2 characters' }
  validates :content, presence: true

  scope :last_some, -> { order(created_at: :desc).limit(20) }

  after_create_commit :broadcast_message

  private

  def broadcast_message
    MessageBroadcastJob.perform_later(self)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :filename, AvatarUploader

  belongs_to :category
  has_many :comments, as: :comment_goal, dependent: :destroy

  validates :name, format: { with: /\./,
                             message: 'should include "."' }
  validates :name, format: { with: /\A[A-Z][a-z]+\s+[A-Z][a-z]+\.?\z/,
                             message: 'should have 2 capital words at least 2 characters' }
  validates :content, presence: true
  validates_size_of :filename, maximum: 2.megabytes, message: "should be less than 2MB"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all.order(:name)
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to category_posts_path(@category), notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to category_posts_path(@category), notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    respond_to do |format|
      format.js do
        @comment = Comment.new(comment_params)
        if @comment.save
          @comments = Comment.last_some.where(comment_goal_type: params[:comment][:comment_goal_type],
                                              comment_goal_id: params[:comment][:comment_goal_id])
          flash[:notice] = 'Comment was successfully created.'
          render :index, format: :js
        else
          flash[:error] = render_to_string(partial: 'shared/active_record_errors',
                                           locals: { object: @comment })
          render partial: 'shared/show_flash'
        end
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :content, :comment_goal_id, :comment_goal_type)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_category, only: [:index, :new, :edit, :create, :update]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.where(category_id: params[:category_id]).order(updated_at: :desc).limit(20)
    #for category comments form
    @comment = @category.comments.new
  end

  def show
    #for post comments form
    @comment = @post.comments.new
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.filename = params[:post][:file]

    if @post.save
      redirect_to category_post_path(@category, @post), notice: 'Post was successfully created.'
    else
      flash[:error] = render_to_string partial: 'shared/active_record_errors', locals: {object: @post}
      render :new
    end
  end

  def update
    @post.filename = params[:post][:file] if params[:post][:file]
    if @post.update(post_params)
      redirect_to category_post_path(@category, @post), notice: 'Post was successfully updated.'
    else
      flash[:error] = render_to_string partial: 'shared/active_record_errors', locals: {object: @post}
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to category_posts_path(params[:category_id]), notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def set_category
      @category = Category.find(params[:category_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :content, :filename, :category_id, :filename_cache)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def twitterized_type(type)
    case type.to_sym
      when :alert
        'warning'
      when :error
        'danger'
      when :notice
        'info'
      when :success
        'success'
      else
        type.to_s
    end
  end

  def cut_text(text, length = 430)
    return text if text.length < length
    text[0..length] + '...'
  end
end

app/views/categories/_form.html.haml
= form_for(@category) do |f|
  .form-group
    = f.label :name
    %br/
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :description
    %br/
    = f.text_area :description, class: 'form-control'
  .form-group.text-right
    = f.submit class: 'btn btn-primary'

app/views/categories/edit.html.haml
- provide(:page_title, 'Editing category')

%ul.pager
  %li.previous
    = link_to '← Back to categories', categories_path

%h1 Editing category
= render 'form'

app/views/categories/index.html.haml
- provide(:page_title, 'All categories')
.panel.panel-default.panel-categories
  .panel-heading
    %h2
      All Blog Categories
      = link_to 'add a new category',
                new_category_path,
                class: 'pull-right lead'
  %ul.list-group
    - if @categories.blank?
      %li.list-group-item
        .lead.text-center
          %br
          No categories yet

    - @categories.each do |category|
      %li.list-group-item
        .lead
          = link_to category.name,
                    category_posts_path(category),
                    title: 'see posts'
          .pull-right.preferences
            = pluralize(category.comments.count, 'comment')
            ,
            = pluralize(category.posts.count, 'post')
            ,
            %em
              = category.updated_at.strftime("Created on %m/%d/%Y at %I:%M%p")
            %span.buttons
              = link_to edit_category_path(category.id),
                        title: 'edit category' do
                %span.glyphicon.glyphicon-pencil
              = link_to category_path(category.id),
                        method: :delete,
                        data: { confirm: 'Are you sure?' },
                        title:  'remove category' do
                %span.glyphicon.glyphicon-remove
        = cut_text category.description

app/views/categories/new.html.haml
- provide(:page_title, 'New category')

%ul.pager
  %li.previous
    = link_to '← Back to categories', categories_path

%h1 New category
= render 'form'

app/views/comments/_comment.html.haml
%ul#comments.comments
  %li.comment
    .clearfix
      %h4.pull-left
        = comment.author
      %p.pull-right
        = time_tag comment.created_at
    %p
      %em
        = comment.content

app/views/comments/_form.html.haml
- remote ||= false
.well
  %h4 Leave a comment
  = form_for(@comment, remote: remote, html: { role: 'form', class: 'clearfix comments_form', id: 'new-comment' }) do |f|
    .form-group
      = f.label :author, class: 'sr-only'
      = f.text_field :author, placeholder: 'Author', class: 'form-control'
    .form-group
      = f.label :content, class: 'sr-only'
      = f.text_area :content,
        placeholder: 'Content',
        class: 'form-control text_comment',
        id: 'comment-body'
    .text-right
      = f.hidden_field :comment_goal_type
      = f.hidden_field :comment_goal_id
      = f.submit 'Send',
        class: 'btn btn-primary submit_comment',
        id: 'comment-submit'

app/views/comments/index.js.erb
$('#flash-messages').append('<%= j render(:partial => 'shared/flash_messages') %>');
$('.own-comments').html('<%= j render @comments %>');
$('#comment_content').val('');

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title #{ yield(:page_title) } | The Blog
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    #flash-messages
      = render partial: 'shared/flash_messages'
    .container.col-md-10.col-md-offset-1
      = yield

app/views/posts/_form.html.haml
= form_for([@category, @post], html: { multipart: true }) do |f|
  .form-group
    = f.label :name
    %br
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :content
    %br
    = f.text_area :content, class: 'form-control'
  .form-group
    = f.label :file
    %br
    = image_tag(@post.filename_url) if @post.filename?
    = f.file_field :file, class: 'form-control'
    = f.hidden_field :filename_cache
  .form-group
    = f.label :category_id
    %br
    = f.select :category_id, options_for_select(Category.order(:name).pluck(:name, :id), params[:category_id]), {}, class: 'form-control'
  .form-group.text-right
    = f.submit class: 'btn btn-primary'

app/views/posts/edit.html.haml
- provide(:page_title, 'Editing post')

%ul.pager
  %li.previous
    = link_to '← Back to posts', category_posts_path

%h1 Editing post
= render 'form'

app/views/posts/index.html.haml
- provide(:page_title, "All post for #{@category.name}")
%ul.pager
  %li.previous
    = link_to '← Back to categories', categories_path
  %li.previous
    = link_to 'add a new post', new_category_post_path

.panel.panel-default
  .panel-heading
    %h2
      %strong
        Posts for category:
      = @category.name
    .lead.category-description
      %strong
        Description:
      = @category.description
  %ul.list-group
    - if @posts.blank?
      %li.list-group-item
        .lead.text-center
          %br
          No posts for category '#{@category.name}' yet

    - @posts.each do |post|
      %li.list-group-item
        .lead
          = link_to post.name,
                    category_post_path(post.category_id, post.id),
                    title: 'see details...'
          .pull-right.preferences
            = pluralize(post.comments.count, 'comment')
            ,
            %em
              = post.updated_at.strftime("Printed on %m/%d/%Y at %I:%M%p")
            %span.buttons
              = link_to edit_category_post_path(post.category_id, post.id),
                        title: 'edit post' do
                %span.glyphicon.glyphicon-pencil
              = link_to category_post_path(post.category_id, post.id),
                        method: :delete,
                        data: { confirm: 'Are you sure?' },
                        title: 'remove post' do
                %span.glyphicon.glyphicon-remove
        = cut_text post.content

= render( partial: 'comments/form', locals: { remote: true })
%h3 Comments:
#comments.own-comments.panel-body{data: {"category-id" => @category.id}}
  = render @category.comments.last_some

app/views/posts/new.html.haml
- provide(:page_title, 'New post')

%ul.pager
  %li.previous
    = link_to '← Back to posts', category_posts_path

%h1 New post
= render 'form'

app/views/posts/show.html.haml
- provide(:page_title, "Post #{@post.name}")
%ul.pager
  %li.previous
    = link_to '← Back to posts', category_posts_path
%h1
  = @post.name
  = link_to edit_category_post_path(@post.category_id, @post.id),
            class: "btn btn-default",
            title: 'edit post' do
    %span.glyphicon.glyphicon-pencil
.row.text-center
  - unless @post.filename.file.nil?
    =image_tag @post.filename.url, class: 'img-thumbnail img-responsive photo'
.row
  %p.lead
    = @post.content

.row
  = render( partial: 'comments/form', locals: { remote: true })
%h3 Comments:
#comments.own-comments.panel-body{data: {"post-id" => @post.id}}
  = render @post.comments.last_some

app/views/shared/_active_record_errors.html.haml
- if object.errors.any?
  #error_explanation1
    %h4
      = pluralize(object.errors.count, "error")
      prohibited this comment from being saved:
    %ul
      - object.errors.full_messages.each do |message|
        %li= message

app/views/shared/_flash_messages.html.haml
- flash.each do |type, message|
  .row.flash-message
    .col-lg-12
      %div{:class => "alert alert-#{twitterized_type(type)} alert-dismissible", :role => "alert"}
        = message
    :javascript
      $('html, body').scrollTop($("#flash-messages").offset().top);
      setTimeout(function(){
        $(".flash-message").fadeTo(500, 0).slideUp(500, function () {
          $(this).remove();
        });
      }, 5000)
- flash.clear

app/views/shared/_show_flash.js.erb
$('#flash-messages').append('<%= j render(:partial => 'shared/flash_messages') %>');